### ISSUE TITLE
Return to main screen link

### ISSUE THREAD

**Issue by OregonFanBoy** [OregonFanBoy/Elemental#1]
Steps to reproduce:
Access Element Lists
Click on link "Return to Main Element Screen"

Expected Result: Element Main screen displays

Actual Result: Error message "File not found"

**Comment by Blythen** [comment]
list.html refered back to the index.html but there was an error.  I fixed this by changing indxe.html to index.html

**Comment by OregonFanBoy** [comment]
Problem resolved.
