### ISSUE TITLE
Earth Element Errors

### ISSUE THREAD

**Issue by OregonFanBoy** [OregonFanBoy/Elemental#3]
Steps to reproduce:
1) Access Earth Element from Elements list.

Expected Results: Information on earth is spelled correctly.

Actual Result: Spelling error on title of Earth.

**Comment by Blythen** [comment]
In the <h1> tags, the code said information on EATRH.  This now says Information on EARTH

**Comment by Blythen** [comment]
Whoops ... I used a < h1 > tag in the last comment and it changed the code.  I did not mean to do this.  The message was suppose to say : 

In the < h1 > tags, the code said information on EATRH.  This now says Information on EARTH

**Comment by OregonFanBoy** [comment]
Spelling is now correct.
Problem resolved.
