### ISSUE TITLE
earth.html link to elements list is incorrect

### ISSUE THREAD

**Issue by Blythen** [OregonFanBoy/Elemental#4]
Steps to reproduce:
Access: View earth.html
Click on link "Return to Main Element Screen"

Expected Result: Show Elements List Screen displayed

Actual Result: Elements Main Screen displayed

**Comment by OregonFanBoy** [comment]
The link was directing to an incorrect page (Element Main Screen).
The link is now directing to Elements List page.

**Comment by Blythen** [comment]
Good job.  That was a tough one ;p
