### ISSUE TITLE
fire.html picture incorrect

### ISSUE THREAD

**Issue by Blythen** [OregonFanBoy/Elemental#5]
Steps to reproduce:
Access: View Fire Element

Expected Results: Fire picture displayed

Actual Result: Water picture displayed

**Comment by OregonFanBoy** [comment]
Image source location was pointing to picture of water.
I updated the image source location to point to fire.
Fire.html now displays a picture of fire.

**Comment by Blythen** [comment]
Awesome Job, Frank!! I'm putting you in for a promotion
