### ISSUE TITLE
Element list items not all same color

### ISSUE THREAD

**Issue by OregonFanBoy** [OregonFanBoy/Elemental#8]
Steps to reproduce:
Accesses Elements List.
View the list.

Expected output: Display Element links in the color of red.

Actual output. All element  links display in color red except the link for Earth.

**Comment by Blythen** [comment]
Changed the tag < a href="earth.html" style="color:blue" >Earth< /a >< br > to < a href="earth.html" style="color:red" >Earth< /a >< br >

**Comment by OregonFanBoy** [comment]
Thanks Neal!
Problem Resolved.
